### ISSUE TITLE
xtk:option

### ISSUE THREAD

**Issue by ScyriusS** [cumpstey/campaign-sync#1]
Donwlod works to extract each option but program finished on error  :
 -m Download -s http://nXXXX:8080/nl/jsp/soaprouter.jsp -u XXX -p XX--dir "C:\Campaign files" --schema xtk:option

Exception non gérée : 
System.NotSupportedException: Le format du chemin d'accès donné n'est pas pris en charge.
   à System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   à System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   à Zone.Campaign.Sync.Services.Downloader.DoDownload(IRequestHandler requestHandler, DownloadSettings settings) dans C:\Dev\AdobeCampaign\campaign-sync-master\Zone.Campaign.Sync.Common\Services\Downloader.cs:ligne 113
   à Zone.Campaign.Sync.UI.Program.Main(String[] args) dans C:\Dev\AdobeCampaign\campaign-sync-master\Zone.Campaign.Sync.UI\Program.cs:ligne 64

**Comment by Rogn** [comment]
Hi @ScyriusS,,
You probably have a path separator ('\\') in the internal name and then an invalid path character within that path section. An example would be "test:\name".

**Comment by ScyriusS** [comment]
Yes you have right but it's ":" character : i have some standard option with the name : WdbcOptions_TableSpaceWork_nms:extAccount:EXT184....

I will integrate an exception to avoid axtraction of this option which is empty
