### ISSUE TITLE
.EXE file ?

### ISSUE THREAD

**Issue by caeypi** [cumpstey/campaign-sync#3]
compiled it

**Comment by ScyriusS** [comment]
When you compil' the project with visual studio code / you found .exe in
root folder so in CampaignSync folder.

**Comment by caeypi** [comment]
Thank you for the help.
I compiled it in release, so now it works in the cmd line tool.
Is there any real UI?

**Comment by cumpstey** [comment]
No gui, if that's what you mean - it's just a commandline tool. The readme describes how to use it.

**Comment by caeypi** [comment]
alright thx

**Comment by ScyriusS** [comment]
Hello , no only commande line and coumentation given on github page.
